version: "3.9"

services:
  db:
    image: cockroachdb/cockroach:latest
    hostname: 'db'
    volumes:
      - ./.dev-data/compose/db:/cockroach/cockroach-data
    command: start-single-node --insecure
    ports:
        - "26257:26257"
        - "8080:8080"
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    links:
      - db
