version: "3.9"

services:
  db:
    image: cockroachdb/cockroach:latest-v21.1
    hostname: 'db'
    volumes:
      - db:/cockroach/cockroach-data
    command: start-single-node --insecure
    ports:
        - "26257:26257"
        - "8080:8080"
    restart: unless-stopped
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - HOLLOW_JWT_AUDIENCE=https://staging.hollow.platformequinix.net
    ports:
      - "8000:8000"
    links:
      - db
    restart: unless-stopped
volumes:
  db:
