version: "3.9"

services:
  db:
    image: cockroachdb/cockroach:latest-v21.1
    hostname: 'db'
    volumes:
      - db:/cockroach/cockroach-data
    command: start-single-node --insecure
    ports:
        - "26257:26257"
        - "8080:8080"
    restart: unless-stopped
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - SERVERSERVICE_OIDC_ENABLED=false
      - SERVERSERVICE_DB_URI="postgresql://root@db:26257/serverservice?sslmode=disable"
    ports:
      - "8000:8000"
    links:
      - db
    restart: unless-stopped
volumes:
  db:
