version: '3.7'

services:
  serverservice:
    depends_on:
      - jaeger
    environment:
      - SERVERSERVICE_TRACING_ENABLED=true
      - SERVERSERVICE_TRACING_PROVIDER=jaeger
      - SERVERSERVICE_TRACING_ENDPOINT=http://jaeger:14268/api/traces
      - SERVERSERVICE_TRACING_ENVIRONMENT=dev-dockercompose

  jaeger:
    image: jaegertracing/all-in-one:1.36.0
    ports:
      - "16686:16686" # The UI port
    networks:
      - hollow
